### ISSUE TITLE
Roadmap to Version 2 aka "Dawn of a Spicy Sheet"

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Spices-Flavours#52]
In order to support all SWADE Versions for FVTT 0.8.x and greater, a new sheet needs to be created.

- [ ] Translation strings for the settings (@SalieriC)
- [x] Add VTTColorSettings as a dependency (@javierriveracastro)
- [x] Use proper color and file pickers for settings (possibly @SalieriC)
- [x] A settings window (with or without tabs) (@javierriveracastro )
- [x] Themes setup (@javierriveracastro)
- [x] Make a working manifest.json (that enables installing the module in Foundry)
- [ ] Select/create (@DocArcane) and use (@SalieriC) sensible background images/colours for the three starting themes.
- [x] Export settings to a .json file
- [x] Import settings from a json file.
- [x] Split CSS into seperate files (@javierriveracastro)
- [x] Add text colour variable(s) (@SalieriC)
- [ ] Style inputs for Wounds and Fatigue (@SalieriC)
- [ ] Creating assets (@DocArcane)

**Comment by javierriveracastro** [comment]
The proper color and file pickers depend on adding Setting Extender AFAIK.

**Comment by SalieriC** [comment]
Keep in mind, that we will need colour pickers that support HEX8/alpha otherwise we can't support transparency, which would be a shame.

**Comment by javierriveracastro** [comment]
Doesn't Setting Extenders support it? Those were the ones that we use in v1, no?

**Comment by SalieriC** [comment]
For the colour pickers he used this: https://github.com/ardittristan/VTTColorSettings
Settings extender we used for file pickers.

**Comment by javierriveracastro** [comment]
Then we need both as prerequisites.

Or no. Since we are going to make a custom config form we don't probably need Settings Extender.

**Comment by javierriveracastro** [comment]
Ok, now settings look a lot cleaner. I'm sure about tabs (I don't know how to organize then, so I will defer it).

**Comment by SalieriC** [comment]
This will become clearer the more configuration options we add, I guess.

**Comment by javierriveracastro** [comment]
Export and import should be working now.

**Comment by SalieriC** [comment]
It gets pretty crowded in the customisation window. We should take a look at adding tabs to it sometime soon @javierriveracastro. I'm thinking similar to the way Dice So Nice does it. We need to decide how to split the options though.

**Comment by javierriveracastro** [comment]
At the start we could probably make four tabs. One generic (empty now) and one for each one of the three main parts (left bar, top bar, and body).

**Comment by SalieriC** [comment]
Nut sure this is the best way of splitting it up. Makes sense of course but we may use some variables in multiple places later on, which might be especially true for text colours and - oh my - different fonts. Where would you put these then? Generic I guess?

**Comment by javierriveracastro** [comment]
No, each one on its zone tab. Like Name Font, Other Top Bar Font, both in TopBar tab.

**Comment by SalieriC** [comment]
You want an individual font and colour for everything? That's quite a lot of stuff but all right.

**Comment by javierriveracastro** [comment]
If we allow for different backgounds for each "part", then we need to allow for different text color in each part.

There is only a little step between allowing different colors and different fonts.
